version: '3.8'

services:
  # Service Nginx
  nginx:
    image: scalp852/nginx:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - front
      - movies-service
      - notifications-service
      - rooms-service
      - search-service
      - sessions-service
      - users-service
    networks:
      - simplo-cine-network

  # Service Frontend (Next.js)
  front:
    image: scalp852/front-app:1.0.0
    ports:
      - "3000:3000"
    networks:
      - simplo-cine-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Service de gestion des films
  movies-service:
    image: scalp852/movies-service:1.0.0
    ports:
      - "3001:3000"
    depends_on:
      - postgres_movies
    environment:
      - DATABASE_URL=postgres://user:password@postgres_movies:5432/movies_db
    networks:
      - simplo-cine-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres_movies:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies_db
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data
    networks:
      - simplo-cine-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d movies_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Service de notifications
  notifications-service:
    image: scalp852/notifications-service:1.0.0
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@postgres_notifications:5432/notifications_db
    networks:
      - simplo-cine-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Service de gestion des salles
  rooms-service:
    image: scalp852/rooms-service:1.0.0
    ports:
      - "3004:3000"
    depends_on:
      - postgres_rooms
    environment:
      - DATABASE_URL=postgres://user:password@postgres_rooms:5432/rooms_db
    networks:
      - simplo-cine-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres_rooms:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rooms_db
    volumes:
      - postgres_data_room:/var/lib/postgresql/data
    networks:
      - simplo-cine-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d rooms_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Service de recherche
  search-service:
    image: scalp852/search-service:1.0.0
    ports:
      - "3005:3000"
    depends_on:
      - postgres_search
    environment:
      - DATABASE_URL=postgres://user:password@postgres_search:5432/search_db
    networks:
      - simplo-cine-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres_search:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: search_db
    volumes:
      - postgres_data_search:/var/lib/postgresql/data
    networks:
      - simplo-cine-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d search_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Service de gestion des sessions
  sessions-service:
    image: scalp852/sessions-service:1.0.0
    ports:
      - "3006:3000"
    depends_on:
      - postgres_sessions
    environment:
      - DATABASE_URL=postgres://user:password@postgres_sessions:5432/sessions_db
    networks:
      - simplo-cine-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres_sessions:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sessions_db
    volumes:
      - postgres_data_session:/var/lib/postgresql/data
    networks:
      - simplo-cine-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sessions_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Service de gestion des utilisateurs
  users-service:
    image: scalp852/users-service:1.0.0
    ports:
      - "3007:3000"
    depends_on:
      - postgres_users
    environment:
      - DATABASE_URL=postgres://user:password@postgres_users:5432/users_db
    networks:
      - simplo-cine-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres_users:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    volumes:
      - postgres_data_user:/var/lib/postgresql/data
    networks:
      - simplo-cine-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d users_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  prometheus:
    image: scalp852/prometheus-service:1.0.0    
    ports:
      - "9090:9090"
    networks:
      - simplo-cine-network

  grafana:
    image: grafana/grafana
    ports:
      - "3010:3000"
    networks:
      - simplo-cine-network

volumes:
  postgres_data_movie:
  postgres_data_room:
  postgres_data_search:
  postgres_data_session:
  postgres_data_user:

networks:
  simplo-cine-network:
    driver: bridge
