name: Build and Push Docker Images

on:
  push:
    branches:
      - develop  # Changez la branche si nécessaire

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push microservice images
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/users-service:1.0.0 ./micro-services/users-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/users-service:1.0.0


    - name: Build and push nginx image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx:1.0.0 ./api/nginx
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx:1.0.0
