name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:

          
  deploy-on-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 45.81.84.133
          username: "adminlocal"
          password: "cdadevops2024"
          port: 9039
          script: |
            # Arrêter tous les conteneurs s'ils existent
            containers=$(sudo docker ps -q)
            if [ -n "$containers" ]; then
              sudo docker stop $containers
            fi

            # Supprimer tous les conteneurs + network s'ils existent
            containers=$(sudo docker ps -a -q)
            if [ -n "$containers" ]; then
              sudo docker rm $containers
              # Supprime le network custom
              sudo docker network rm simplo-cine_simplo-cine-network
            fi

            # Vérifier si le répertoire existe, sinon le cloner
            if [ ! -d ~/devops/simplo-cine ]; then
              mkdir -p ~/devops
              git clone --branch develop https://github.com/rider974/simplo-cine-dockerhub-ci ~/devops/simplo-cine
            else
              cd ~/devops/simplo-cine
              # Réinitialiser les changements locaux à l'état de la branche distante
              git pull origin develop
            fi

  build-and-run-on-vps:
    runs-on: ubuntu-latest
    needs: deploy-on-vps

    steps:
      - name: Build Docker Containers
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 45.81.84.133
          username: "adminlocal"
          password: "cdadevops2024"
          port: 9039
          script: |
            cd ~/devops/simplo-cine
            sudo docker network rm simplo-cine_simplo-cine-network
            sudo docker-compose down
            sudo docker-compose build --parallel

      - name: Start Docker Containers
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 45.81.84.133
          username: "adminlocal"
          password: "cdadevops2024"
          port: 9039
          script: |
            cd ~/devops/simplo-cine
            sudo docker network rm simplo-cine_simplo-cine-network
            sudo docker-compose up --build -d

